 <div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper form-horizontal">
            <div class="content solo-page">
                <h3 class="title-editor border-blue text-center">
                    <?php echo  p__("listcheckin", "Manage Qr Code"); ?>

                <a href="/listcheckin/locations/create"
                class="color-blue btn sb-tour pull-right" style="margin-right:16px;">
                    <?php echo  p__("listcheckin", "Create a New QR"); ?>
                </a>

                </h3>
                <div class="subcontent content-color container-fluid">
                    <div class="form-group">
                     <div class="col-md-12">
                          <table id="dynamic-locations"
                                   class="table content-white-bkg sb-pager">
                                <thead>
                                    <tr class="border-grey">
                                        <th data-dynatable-column="id"
                                            style="width: 5%;"><?php echo  p__("listcheckin", "ID"); ?></th>
                                        <th data-dynatable-column="first_name"
                                            style="width: 20%;"><?php echo  p__("listcheckin", "Name"); ?></th>
                                        <th style="width: 5%;"><?php echo  p__("listcheckin", "In"); ?></th>
                                        <th style="width: 12%;"><?php echo  p__("listcheckin", "Check-In"); ?></th>
                                        <th style="width: 12%;"><?php echo  p__("listcheckin", "Check-Out"); ?></th> 
                                        <th data-dynatable-column="status"
                                            style="width: 10%;"><?php echo  p__("listcheckin", "Status"); ?></th>
                                       <th data-dynatable-column="allow_scan"
                                            style="width: 10%;"><?php echo  p__("listcheckin", "Members Scan"); ?></th>
                                       <th data-dynatable-column="created_at"
                                            style="width: 10%;"><?php echo  p__("listcheckin", "Created At"); ?></th>
                                       <th><?php echo  p__("listcheckin", "Action"); ?></th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.css"
      media="screen"
      rel="stylesheet"
      type="text/css">
<script type="text/javascript"
        src="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.js"></script>

<style type="text/css">
    #dynamic-leaves {
        margin-top: 15px;
    }
</style>

<script type="text/javascript">
    var uriParams = {};
    let rowTemplate = `
    <tr class="dynarow">
        <td>#(ID)</td>
        <td>(NAME)</td>
        <td>(IS_IN_SHOP)</td>
        <td>
            <a target="_blank" btn btn-xs btn-default" href="/listcheckin/locations/qrcode/value_id/(VALUEID)/id/(ID)/type/checkin">
             <i class="fa fa-qrcode" aria-hidden="true"></i>
            </a>
        </td>
        <td>
            <a target="_blank" btn btn-xs btn-default" href="/listcheckin/locations/qrcode/value_id/(VALUEID)/id/(ID)/type/checkout">
             <i class="fa fa-qrcode" aria-hidden="true"></i>
            </a>
        </td>
        <td>(STATUS)</td>
        <td>(ALLOW)</td>
        <td>(DATE)</td>       
        <td>
           <a href="/listcheckin/locations/members/id/(ID)"
               class="btn btn-xs btn-primary members-location (IS_MEMBER)">
                <?php echo p__("listcheckin", "MEMBERS") ?>
            </a>
           <a href="/listcheckin/locations/edit/id/(ID)"
               class="btn btn-xs btn-info edit-location">
                <?php echo p__("listcheckin", "EDIT") ?>
            </a>
            <a href="/listcheckin/locations/delete/id/(ID)"
               class="btn btn-xs btn-danger delete-location">
                <?php echo p__("listcheckin", "DELETE") ?>
            </a>
             <a href="/listcheckin/manager/list/id/(ID)"
               class="btn btn-xs btn-warning manager-location">
                <?php echo p__("listcheckin", "MANAGERS") ?>
            </a>
        </td>
     </tr>`;

    function rowWriter(rowIndex, record, columns, cellWriter) {
        return rowTemplate
            .replace(/\(ID\)/g, record.id)
            .replace(/\(NAME\)/g, record.name)
            .replace(/\(QR\)/g, record.qr_code)
            .replace(/\(DATE\)/g, record.created_at)
            .replace(/\(VALUEID\)/g, record.value_id)
            .replace(/\(ALLOW\)/g, record.allow_scan)
            .replace(/\(IS_MEMBER\)/g, record.is_member)
            .replace(/\(IS_IN_SHOP\)/g, record.in_shop_total)            
            .replace(/\(STATUS\)/g, record.status);
    }
    $.dynatableSetup({
        table: {
            defaultColumnIdStyle: 'noStyle'
        },
        features: {
            paginate: true,
            sort: true,
            pushState: true,
            search: true,
            recordCount: true,
            perPageSelect: false,
        },
    });

    let tableCustomers = $('#dynamic-locations');

    tableCustomers.bind('dynatable:preinit', function(e, dynatable) {
        dynatable.utility.textTransform.noStyle = function(text) {
            return text;
        };
    });
  
 
    tableCustomers.bind('dynatable:afterProcess', function (e, data) {
        uriParams = data.queries;
    });
    

    tableCustomers.bind('dynatable:push', function(e, dynatable) {
          uriParams = dynatable.queries;   
    });

    // And on the table listcheckin
    tableCustomers.dynatable({
        dataset: {
            ajax: true,
            ajaxUrl: '/listcheckin/locations/fetch-all',
            ajaxOnLoad: true,
            records: [],
            perPageDefault: 25
        },
        inputs: {
            processingText: '<?php echo __jss("Loading ...") ?>',
            searchPlaceholder: '<?php echo __jss("Search by name ...") ?>',
            recordCountText: '<?php echo __jss("Showing") ?> ',
            filteredFrom: ' (<?php echo __jss("filtered from #TOTAL# total records") ?>)',
            recordText: '<?php echo __jss("record") ?>',
            recordTextPlural: '<?php echo __jss("records") ?>',
            textOf: '<?php echo __jss("of") ?>',
            textTo: '<?php echo __jss("to") ?>',
            queries: $('.dt-search')
        },
        writers: {
            _rowWriter: rowWriter
        }
    });

    $(document).ready(function() {
        if($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']) {
            $.datepicker.setDefaults($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']);
        } else {
            $.datepicker.setDefaults($.datepicker.regional['en']);
        }
    });


    $(document).off("click", ".delete-location");
    $(document).on("click", ".delete-location", function (e) {
        e.preventDefault();
        let deleteHref = $(this).attr("href");
        swal({
            title: '<?php echo P__("listcheckin", "Confirmation") ?>',
            text: '<?php echo P__("listcheckin", "Are you sure you want to delete this Shop?") ?>',
            showCancelButton: true,
            confirmButtonColor: '#0099C7',
            confirmButtonText: '<?php echo P__("listcheckin", "Yes, delete!")?>',
            cancelButtonText: '<?php echo P__("listcheckin", "No, go back") ?>',
            buttons: true
        }, function(value) {
            if (!value) {
                return false;
            }

            formget(deleteHref,
                {},
                function (data) {
                    feature_form_success(data.message);
                   // Reload only on success and when done!
                    setTimeout(function () {
                        location.reload();
                    }, 1500)
                },
                function (data) {
                    feature_form_error(JSON.parse(data.responseText).message);
                },
                false);
        });
    });

</script>
 