<?php $location = $this->getLocations(); ?>

<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper form-horizontal">
            <div class="content solo-page">
                <h3 class="title-editor border-blue text-center">
                    <?php echo  p__("listcheckin", "Members of %s", $location->getName()); ?>

                <a href="/listcheckin/locations/list"
                class="color-blue btn sb-tour pull-right">
                    <?php echo  p__("listcheckin", "Back"); ?>
                </a>

                </h3>
                <div class="subcontent content-color container-fluid">
                    <div class="form-group">
                     <div class="col-md-12">
                          <table id="dynamic-locations"
                                   class="table content-white-bkg sb-pager">
                                <thead>
                                    <tr class="border-grey">
                                        <th data-dynatable-column="id"
                                            style="width: 10%;"><?php echo  p__("listcheckin", "ID"); ?></th>
                                        <th data-dynatable-column="first_name"
                                            style="width: 30%;"><?php echo  p__("listcheckin", "Name"); ?></th>
                                        <th style="width: 30%;"><?php echo  p__("listcheckin", "Email"); ?></th>
                                        <th data-dynatable-column="created_at"
                                            style="width: 15%;"><?php echo  p__("listcheckin", "Created At"); ?></th>
                                       <th><?php echo  p__("listcheckin", "Action"); ?></th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.css"
      media="screen"
      rel="stylesheet"
      type="text/css">
<script type="text/javascript"
        src="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.js"></script>

<style type="text/css">
    #dynamic-leaves {
        margin-top: 15px;
    }
</style>

<script type="text/javascript">
    var uriParams = {};
    let rowTemplate = `
    <tr class="dynarow">
        <td>#(CUSTOMER_ID)</td>
        <td>(NAME)</td>
        <td>(EMAIL)</td>
        <td>(DATE)</td>       
        <td>
           <a href="/listcheckin/locations/add-customer/location_id/(LOCATION_ID)/customer_id/(CUSTOMER_ID)"
               class="btn btn-xs btn-info add-member (ADD_HIDE)">
                <?php echo __js("ADD") ?>
            </a>
            <a href="/listcheckin/locations/remove-customer/location_id/(LOCATION_ID)/customer_id/(CUSTOMER_ID)"
               class="btn btn-xs btn-danger remove-memeber (REMOVE_HIDE)">
                <?php echo __js("REMOVE") ?>
            </a>
        </td>
     </tr>`;

    function rowWriter(rowIndex, record, columns, cellWriter) {
        return rowTemplate
            .replace(/\(CUSTOMER_ID\)/g, record.customer_id)
            .replace(/\(LOCATION_ID\)/g, record.location_id)   
            .replace(/\(NAME\)/g, record.name)            
            .replace(/\(DATE\)/g, record.registration_date)
            .replace(/\(ADD_HIDE\)/g, record.is_add_hide)
            .replace(/\(REMOVE_HIDE\)/g, record.is_remove_hide)
            .replace(/\(EMAIL\)/g, record.email);
    }
    $.dynatableSetup({
        table: {
            defaultColumnIdStyle: 'noStyle'
        },
        features: {
            paginate: true,
            sort: true,
            pushState: true,
            search: true,
            recordCount: true,
            perPageSelect: false,
        },
    });

    let tableCustomers = $('#dynamic-locations');

    tableCustomers.bind('dynatable:preinit', function(e, dynatable) {
        dynatable.utility.textTransform.noStyle = function(text) {
            return text;
        };
    });
  
 
    tableCustomers.bind('dynatable:afterProcess', function (e, data) {
        uriParams = data.queries;
    });
    

    tableCustomers.bind('dynatable:push', function(e, dynatable) {
          uriParams = dynatable.queries;   
    });

    // And on the table attendance/leave/list
    tableCustomers.dynatable({
        dataset: {
            ajax: true,
            ajaxUrl: '/listcheckin/locations/fetch-all-customers/location_id/<?php echo $location->getId(); ?>',
            ajaxOnLoad: true,
            records: [],
            perPageDefault: 25
        },
        inputs: {
            processingText: '<?php echo __jss("Loading ...") ?>',
            searchPlaceholder: '<?php echo __jss("Search by name ...") ?>',
            recordCountText: '<?php echo __jss("Showing") ?> ',
            filteredFrom: ' (<?php echo __jss("filtered from #TOTAL# total records") ?>)',
            recordText: '<?php echo __jss("record") ?>',
            recordTextPlural: '<?php echo __jss("records") ?>',
            textOf: '<?php echo __jss("of") ?>',
            textTo: '<?php echo __jss("to") ?>',
            queries: $('.dt-search')
        },
        writers: {
            _rowWriter: rowWriter
        }
    });

    $(document).ready(function() {
        if($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']) {
            $.datepicker.setDefaults($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']);
        } else {
            $.datepicker.setDefaults($.datepicker.regional['en']);
        }
    });


    $(document).off("click", ".add-member");
    $(document).on("click", ".add-member", function (e) {
        e.preventDefault();
        let deleteHref = $(this).attr("href");
        swal({
            title: '<?php echo P__("listcheckin", "Confirmation") ?>',
            text: '<?php echo P__("listcheckin", "Are you sure you want to Add this customer?") ?>',
            showCancelButton: true,
            confirmButtonColor: '#0099C7',
            confirmButtonText: '<?php echo P__("listcheckin", "Yes!")?>',
            cancelButtonText: '<?php echo P__("listcheckin", "No") ?>',
            buttons: true
        }, function(value) {
            if (!value) {
                return false;
            }

            formget(deleteHref,
                {},
                function (data) {
                    feature_form_success(data.message);
                   // Reload only on success and when done!
                    setTimeout(function () {
                        location.reload();
                    }, 1000)
                },
                function (data) {
                    feature_form_error(JSON.parse(data.responseText).message);
                },
                false);
        });
    });

    $(document).off("click", ".remove-memeber");
    $(document).on("click", ".remove-memeber", function (e) {
        e.preventDefault();
        let deleteHref = $(this).attr("href");
        swal({
            title: '<?php echo P__("listcheckin", "Confirmation") ?>',
            text: '<?php echo P__("listcheckin", "Are you sure you want to Remove this customer?") ?>',
            showCancelButton: true,
            confirmButtonColor: '#0099C7',
            confirmButtonText: '<?php echo P__("listcheckin", "Yes!")?>',
            cancelButtonText: '<?php echo P__("listcheckin", "No") ?>',
            buttons: true
        }, function(value) {
            if (!value) {
                return false;
            }

            formget(deleteHref,
                {},
                function (data) {
                    feature_form_success(data.message);
                   // Reload only on success and when done!
                    setTimeout(function () {
                        location.reload();
                    }, 1000)
                },
                function (data) {
                    feature_form_error(JSON.parse(data.responseText).message);
                },
                false);
        });
    });

</script>
 